# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Rmap
version:      0.62
version_from: lib/Data/Rmap.pm
installdirs:  site
requires:
    Scalar::Util:                  0
    Test::Exception:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
