--- #YAML:1.0
name: Data-Rmap
version: 0.61
author:
  - |-
    Brad Bowman E<lt>rmap@bereft.netE<gt>
    Copyright (C) 2004 All rights reserved.
abstract: recursive map, apply a block to a data structure
license: perl
requires:
  Scalar::Util: 0
  Test::Exception: 0
provides:
  Data::Rmap:
    file: lib/Data/Rmap.pm
    version: 0.61
generated_by: Module::Build version 0.26
